### ISSUE TITLE
Undefined `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by pawamoy** [tinted-theming/base16-builder-ruby#4]
Hi, I have this issue when I try to build with `./builder`:

```
building out/colors/base16-porple.kak
/media/pawamoy/Data/git/pawamoy/pawamoy.github.io/base16-builder-ruby/src/template.rb:52:in `block in build_template_data': undefined method `[]' for nil:NilClass (NoMethodError)
	from /media/pawamoy/Data/git/pawamoy/pawamoy.github.io/base16-builder-ruby/src/template.rb:49:in `each'
	from /media/pawamoy/Data/git/pawamoy/pawamoy.github.io/base16-builder-ruby/src/template.rb:49:in `build_template_data'
	from /media/pawamoy/Data/git/pawamoy/pawamoy.github.io/base16-builder-ruby/src/template.rb:25:in `block in render'
	from /media/pawamoy/Data/git/pawamoy/pawamoy.github.io/base16-builder-ruby/src/template.rb:24:in `each'
	from /media/pawamoy/Data/git/pawamoy/pawamoy.github.io/base16-builder-ruby/src/template.rb:24:in `render'
	from ./builder:51:in `block (2 levels) in build'
	from ./builder:50:in `each'
	from ./builder:50:in `block in build'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:484:in `call_with_index'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:453:in `process_incoming_jobs'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:435:in `block in worker'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:426:in `fork'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:426:in `worker'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:417:in `block in create_workers'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:416:in `each'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:416:in `each_with_index'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:416:in `create_workers'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:358:in `work_in_processes'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:264:in `map'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/parallel-1.11.1/lib/parallel.rb:217:in `each'
	from ./builder:49:in `build'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/pawamoy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from ./builder:59:in `<main>'
```

I tried with both Ruby 2.3.3 and 2.4.0, same issue.

**Comment by obahareth** [comment]
Hey @Pawamoy, I'll look into it. Meanwhile you can try my [Elixir builder](https://github.com/obahareth/base16-builder-elixir) instead if you really need to build. I just tested it with no issues.

**Comment by obahareth** [comment]
Hey @Pawamoy, this should be fixed now. Could you give it a go and let me know if it works for you?

**Comment by pawamoy** [comment]
Yup @obahareth, it worked! Thanks!
